# version: 2
#  jobs:
#    build:
#      docker:
#        - image: circleci/node:12.14.0
#      steps:
#        - checkout
#        - run: echo "A first hello"

version: 2.1
orbs:
  node: circleci/node@1.1.6
jobs:
  build-and-test:
    executor:
      name: node/default
    steps:
      - checkout
      - node/with-cache:
          steps:
            - run: npm install
            - run: npm test
workflows:
  build-and-test:
    jobs:
      - build-and-test
